export const routes = {
  home: "/",
  shop: "/blumen",
  category: (slug: string) => (slug === "alle" ? "/blumen" : `/blumen/${slug}`),
  product: (slug: string) => `/produkt/${slug}`,
  occasions: "/anlaesse",
  occasion: (slug: string) => `/anlaesse/${slug}`,
  extras: "/geschenksets",
  subscription: "/blumen-abo",
  delivery: "/lieferung",
  about: "/ueber-uns",
  contact: "/kontakt",
  faq: "/faq",
  tracking: "/bestellung-verfolgen",
  account: "/konto",
  cart: "/warenkorb",
  checkout: "/checkout",
  search: "/suche",
  legal: { imprint: "/impressum", privacy: "/datenschutz", terms: "/agb", withdrawal: "/widerruf" },
  admin: "/admin",
} as const;
